FROM mcr.microsoft.com/devcontainers/javascript-node:1-22-bookworm
RUN apt-get update

# Install Expo CLI globally
RUN npm install -g expo-cli

# Install Firebase
RUN npm install firebase

# Expose ports expo runs on
EXPOSE 8001

