
name: Node.js CI

on:
  push:
    branches: [ Deployment/CI-CD ]
  pull_request:
    branches: [ Deployment/CI-CD  ]

# Grant the necessary permission to workflow
permissions:
  pages: write 
  id-token: write

jobs:
  # Test workflow
  # test:
  #   runs-on: ubuntu-latest
  #   strategy:
  #     matrix:
  #       node-version: [16.x]
  #   steps:
  #   # - name: Check out Branch
  #   #   uses: actions/checkout@v2

  #   # # use self-define steps to load env
  #   # - name: Load Node.js
  #   #   uses: ./.github/actions/setup-and-install
  #   #   with:
  #   #     node-version: ${{ matrix.node-version }}

  #   # - name: Running Test
  #   #   run: npm run test

  # Build workflow 
  # - No actual build workflow since using github-page
  #   #   run: npx expo export -p web  

  # Deployment workflow
  build-and-deploy:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x]
    steps:
    - name: Check out Branch
      uses: actions/checkout@v2
      
    # use self-define steps to load env
    - name: Load Node.js
      uses: ./.github/actions/setup-and-install
      with:
        node-version: ${{ matrix.node-version }}

    - name: Build Expo project
      run: npx expo export -p web 

    - name: Deploy to github page
      uses: actions/deploy-pages@v4
      with:
        token: ${{ github.token }}