
name: Node.js CI

on:
  push:
    branches: [ Deployment/CI-CD ]
  pull_request:
    branches: [ Deployment/CI-CD  ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.x, 12.x, 14.x]

    steps:
    - name: Check out Branch
      uses: actions/checkout@v2
      
    - name: Set-Up Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
        
    - name: Install package
      run: npm ci
    - run: npm install react-scripts

    - name: Running Test
      run: npm test

    - name: Building Project
      run: npm run build
