
name: Node.js CI

on:
  push:
    branches: [ Deployment/CI-CD ]
  pull_request:
    branches: [ Deployment/CI-CD  ]


jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x]
    steps:
    - name: Check out Branch
      uses: actions/checkout@v2
    - name: Set-Up Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Install package
      run: npm install

    - name: Running Test
      run: npm run test
      # uses: willcaul/jest-github-action@v4
      # env:
      #   GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      # with:
      #   # this is just an example, this could be any command that will trigger jest
      #   test-command: "npm run test"
      #   changes-only: true

  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x]
    needs: test
    steps:
    - name: Check out Branch
      uses: actions/checkout@v2
    - name: Set-Up Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Install package
      run: npm install
    
    - name: Building Project
      run: npm run build
