
name: Node.js CI

on:
  # push:
  #   branches: [ Deployment/CI-CD_RenderUnitTest_HL]
  # pull_request:
  #   branches: [ Deployment/CI-CD_RenderUnitTest_HL ]
  push:
    branches: [dev]
  pull_request:
    branches: [dev]

env:
  NODE_VERSION: 20.17.x
  
# Grant the necessary permission to workflow
permissions:
  contents: read
  pages: write 
  id-token: write

jobs:
  # Test workflow
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Check out Branch
      uses: actions/checkout@v2

    # use self-define steps to load env
    - name: Load Node.js
      uses: ./.github/actions/setup-and-install
      with:
        node-version: ${{ env.NODE_VERSION }}

    - name: Running Test
      run: npm run test